version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - healthmates-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  healthmates-network:
    driver: bridge
